os:
  - linux

language: php

# menggunakan distro yang trusty
dist: trusty

php: 
  - '7.1'

services: 
  - docker

# task yang dilakukan
jobs:
  include:
    #tahapan testing
    - stage: "Tests"
      name:  "Unit Test PHP"
      script:
      - travis_retry composer self-update
      - travis_retry composer install --prefer-source --no-interaction
      - cp .env.example .env
      - vendor/bin/phpunit tests/ExampleTest.php
    # tahapan build image dan push ke dockerhub
    - stage: "Build Docker Image"
      name: "Build Images Docker"
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-stages-demo .
      - docker images
      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/tugas-cicd
      - docker push $DOCKER_USERNAME/tugas-cicd
